

name: GIT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

    
  pull_request:
    types: [closed]
    
  workflow_dispatch: 
    




jobs:
  # This workflow contains a single job called "build"
  build:
  
    runs-on: macos-latest

    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      
      - name: creating a file 
        run: echo file 2 created >file2.txt
        
      - name: displaying the contents
        run: cat file2.txt
           
      - run : |
             cp file1.txt file2.txt
             cat file2.txt
        
      - uses : actions/upload-artifact@v3
        with:
             name: my-artifact
             path: file2.txt
             
             
  job_2:
   
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
             name: my-artifact
             
      - run: echo file3>file3.txt  
             
      - run: cp file2.txt file3.txt

      - uses : actions/upload-artifact@v3
        with :
             name: my-artifact2
             path: file3.txt
  job_3:

 
 
     runs-on: macos-latest
     steps:
     
        - name: file path 
          run: | 
                pwd  
                ls

        - uses : actions/upload-artifact@v3

          with :
             name : my-artifact3  
             path: /Users/runner/work/gitActions-/file1.txt
           
       
        
           
     
      

    
     
          
          
